In [3]:
import jieba
raw_text="""我爱上海
            她喜欢北京"""
stoplist=[' ','\n']
words=list(jieba.cut(raw_text))
words=[i for i in words if i not in stoplist]
words
word_to_ix={i:word for i,word in enumerate(set(words))}
word_to_ix

{0: '北京', 1: '喜欢', 2: '上海', 3: '她', 4: '爱', 5: '我'}

In [13]:
from torch import nn
import torch
embeds=nn.Embedding(6,8)
lists=[]
for k,v in word_to_ix.items():
    tensor_value=torch.tensor(k)
    lists.append((embeds(tensor_value).data))

lists

[tensor([ 1.5649, -0.2076,  1.2371,  1.2551,  0.2258, -0.0281, -0.8688, -1.2265]),
 tensor([ 0.4838,  1.4772,  0.9832, -0.6484, -0.4338, -1.5786,  0.4542, -0.2898]),
 tensor([ 1.2596,  0.2039,  1.1723, -0.2833, -0.6324,  0.2152, -1.4667,  0.3953]),
 tensor([-1.2355,  0.2418,  0.9343, -1.5218, -1.1191, -0.0041,  0.5081,  0.3493]),
 tensor([ 0.7845,  0.9311,  1.7612,  0.4973, -0.5751,  0.3439,  1.0793,  1.1329]),
 tensor([ 0.9145, -2.8861,  1.3695,  2.0318, -0.2937, -0.6854,  0.0041,  0.7340])]