In [1]:
import numpy as np
lst1=[3.14,2.17,0,1,2]
nd1=np.array(lst1)
print(nd1)
print(type(nd1))

[3.14 2.17 0.   1.   2.  ]
<class 'numpy.ndarray'>


In [7]:
import numpy as np
nd3=np.random.random([3,3])
print(nd3)

[[0.63179202 0.44025718 0.08372648]
 [0.71233018 0.42786349 0.2977805 ]
 [0.49208478 0.74029639 0.35772892]]


In [5]:
import numpy as np
np.random.seed(123)#固定种子生成同一份数据
nd4=np.random.randn(2,3)
print(nd4)
np.random.shuffle(nd4)
print("随机打乱后的数据：")
print(nd4)
print(type(nd4))

[[-1.0856306   0.99734545  0.2829785 ]
 [-1.50629471 -0.57860025  1.65143654]]
随机打乱后的数据：
[[-1.50629471 -0.57860025  1.65143654]
 [-1.0856306   0.99734545  0.2829785 ]]
<class 'numpy.ndarray'>


In [9]:
import numpy as np
print(np.linspace(0.1,1,10))

[0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [11]:
import numpy as np 
print(np.arange(1,4,0.5))

[1.  1.5 2.  2.5 3.  3.5]


In [30]:
import numpy as np
np.random.seed(2019)
nd1=np.random.random([10])
print(nd1)
print(nd1[3])
print(nd1[3:6])
print(nd1[1:6:2])
print(nd1[::-2])
nd2=np.arange(25).reshape([5,5])
print(nd2)
print(nd2[1:3,1:3])
print(nd2[(nd2>2)&(nd2<16)])
print(nd2[[1,2]])
print(nd2[[1,2],:])
print(nd2[1:3,:])

[0.90348221 0.39308051 0.62396996 0.6378774  0.88049907 0.29917202
 0.70219827 0.90320616 0.88138193 0.4057498 ]
0.6378774010222266
[0.6378774  0.88049907 0.29917202]
[0.39308051 0.6378774  0.29917202]
[0.4057498  0.90320616 0.29917202 0.6378774  0.39308051]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 6  7]
 [11 12]]
[ 3  4  5  6  7  8  9 10 11 12 13 14 15]
[[ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 5  6  7  8  9]
 [10 11 12 13 14]]


In [39]:
import numpy as np
from numpy import random as nr 
a=np.arange(1,25,dtype=float)
print(np.arange(1,25,dtype=float))
c1=nr.choice(a,size=(3,4))
print(c1)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20. 21. 22. 23. 24.]
[[ 7.  2. 19.  9.]
 [20. 24.  8.  8.]
 [17.  4. 21. 18.]]


In [42]:
#Numpy的算术运算
import numpy as np 
A=np.array([[1,2],[2,3]])
B=np.array([[2,3],[4,5]])
print(A*B)
print(np.dot(A,B))

[[ 2  6]
 [ 8 15]]
[[10 13]
 [16 21]]


In [49]:
import numpy as np
a=np.floor(10*np.random.random([3,4]))
print(a)
print(a.flatten())

[[8. 1. 4. 1.]
 [4. 4. 3. 3.]
 [2. 3. 5. 1.]]
[8. 1. 4. 1. 4. 4. 3. 3. 2. 3. 5. 1.]


In [55]:
#降维
import numpy as np
arr = np.arange(3).reshape(3,1)
print(arr.shape)
print(arr.squeeze().shape)

(3, 1)
(3,)


In [61]:
#合并函数
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.append(a,b)
print(c)
print(c.T)

[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [67]:
import numpy as np
a=np.array([[1,2],[3,4]])
b=np.array([[1,2,3,4]])
print(b)
print(b.T)
b=np.array([[1,2]])
c=np.concatenate((a,b.T),axis=1)
print(c)

[[1 2 3 4]]
[[1]
 [2]
 [3]
 [4]]
[[1 2 1]
 [3 4 2]]


In [71]:
import numpy as np
data_train=np.random.randn(10000,2,3)
# print(data_train)
np.random.shuffle(data_train)
batch_size=100
print(data_train[0])
print(np.sum(data_train[0]))
for i in range(0,len(data_train),batch_size):
    x_batch_sum=np.sum(data_train[i:i+batch_size])
    print("第{}批次，该批次的数据之和：{}".format(i,x_batch_sum))

[[-0.4578903   0.28260193 -1.18269001]
 [ 0.67872069 -1.39534595 -0.42968289]]
-2.5042865199377085
第0批次，该批次的数据之和：2.7069042933790666
第100批次，该批次的数据之和：-54.18349238111581
第200批次，该批次的数据之和：-13.074381372802353
第300批次，该批次的数据之和：19.325454575014337
第400批次，该批次的数据之和：6.505024797368328
第500批次，该批次的数据之和：49.183025108067
第600批次，该批次的数据之和：0.7968163361554117
第700批次，该批次的数据之和：-59.91768852712439
第800批次，该批次的数据之和：32.63611893278524
第900批次，该批次的数据之和：35.32923814164977
第1000批次，该批次的数据之和：-6.961597724641603
第1100批次，该批次的数据之和：-21.59957712574384
第1200批次，该批次的数据之和：14.483862061751854
第1300批次，该批次的数据之和：34.55338620060068
第1400批次，该批次的数据之和：9.317319378985397
第1500批次，该批次的数据之和：-7.339224384738879
第1600批次，该批次的数据之和：-4.598966276897039
第1700批次，该批次的数据之和：-30.847826101305877
第1800批次，该批次的数据之和：-37.02341791131435
第1900批次，该批次的数据之和：28.026239859949285
第2000批次，该批次的数据之和：-81.76641630739587
第2100批次，该批次的数据之和：1.4422594801604327
第2200批次，该批次的数据之和：-37.144193079566925
第2300批次，该批次的数据之和：4.607255461689331
第2400批次，该批次的数据之和：8.665014581263634
第2500批次，该批次的数据之和：19.